[versions]
agp = "8.1.0"
dexKit = "1.1.8"
ezXHelper = "2.0.6"
kotlin = "1.9.0"
xposed = "82"

[libraries]
dexKit = { module = "org.luckypray:DexKit", version.ref = "dexKit" }
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezXHelper" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

